from model import ModelConfig, ModelPipeline

col_to_remove = [
    "Date_of_Enrollment",
    "Time_of_symptom_onset 🔒",
    "Time_symptoms_were_recognized 🔒",
    "Time_last_known_well_(LKW) 🔒",
    "Date/Time_Blood_Drawn_",
    "blooddrawdiff",
    "MoCA_V2",
    "MoCA_V3",
    "MoCA_V4",
    "MoCA_V5",
    "6mo_imaging",
    "30mo_imaging",
    "Qualifying_Stroke_Date",
    "V3_Date",
    "V4_Date",
    "V5_Date",
    "V3_Post_Stroke_Days",
    "V4_Post_Stroke_Days",
    "V5_Post_Stroke_Days",
    "TimePoint.x",
    "I_feel_fatigued.x",
    "I_feel_weak_all_over.x",
    "I_feel_listless_('washed_out').x",
    "I_feel_tired.x",
    "I_have_trouble_starting_things_because_I_am_tired.x",
    "I_have_trouble_finishing_things_because_I_am_tired.x",
    "I_have_energy.x",
    "I_am_able_to_do_my_usual_activities.x",
    "I_need_to_sleep_during_the_day.x",
    "I_am_too_tired_to_eat.x",
    "I_need_help_doing_my_usual_activities.x",
    "I_am_frustrated_by_being_too_tired_to_do_the_things_I_want_to_do.x",
    "I_have_to_limit_my_social_activity_because_I_am_tired.x",
    "FACIT_Fatigue_Scale_Total_(prorated,_if_answers_missing)_.x",
    "Are_you_basically_satisfied_with_your_life?.x",
    "Have_you_dropped_many_of_your_activities_and_interests?.x",
    "Do_you_feel_that_your_life_is_empty?.x",
    "Do_you_often_get_bored?.x",
    "Are_you_in_good_spirits_most_of_the_time?.x",
    "Are_you_afraid_that_something_bad_is_going_to_happen_to_you?.x",
    "Do_you_feel_happy_most_of_the_time?.x",
    "Do_you_often_feel_helpless?.x",
    "Do_you_prefer_to_stay_at_home,_rather_than_going_out_and_doing_things?.x",
    "Do_you_feel_that_you_have_more_problems_with_memory_than_most?.x",
    "Do_you_think_it_is_wonderful_to_be_alive_now?.x",
    "Do_you_feel_worthless_the_way_you_are_now?.x",
    "Do_you_feel_full_of_energy?.x",
    "Do_you_feel_that_your_situation_is_hopeless?.x",
    "Do_you_think_that_most_people_are_better_off_than_you_are?.x",
    "TimePoint.y",
    "I_feel_fatigued.y",
    "I_feel_weak_all_over.y",
    "I_feel_listless_('washed_out').y",
    "I_feel_tired.y",
    "I_have_trouble_starting_things_because_I_am_tired.y",
    "I_have_trouble_finishing_things_because_I_am_tired.y",
    "I_have_energy.y",
    "I_am_able_to_do_my_usual_activities.y",
    "I_need_to_sleep_during_the_day.y",
    "I_am_too_tired_to_eat.y",
    "I_need_help_doing_my_usual_activities.y",
    "I_am_frustrated_by_being_too_tired_to_do_the_things_I_want_to_do.y",
    "I_have_to_limit_my_social_activity_because_I_am_tired.y",
    "FACIT_Fatigue_Scale_Total_(prorated,_if_answers_missing)_.y",
    "Are_you_basically_satisfied_with_your_life?.y",
    "Have_you_dropped_many_of_your_activities_and_interests?.y",
    "Do_you_feel_that_your_life_is_empty?.y",
    "Do_you_often_get_bored?.y",
    "Are_you_in_good_spirits_most_of_the_time?.y",
    "Are_you_afraid_that_something_bad_is_going_to_happen_to_you?.y",
    "Do_you_feel_happy_most_of_the_time?.y",
    "Do_you_often_feel_helpless?.y",
    "Do_you_prefer_to_stay_at_home,_rather_than_going_out_and_doing_things?.y",
    "Do_you_feel_that_you_have_more_problems_with_memory_than_most?.y",
    "Do_you_think_it_is_wonderful_to_be_alive_now?.y",
    "Do_you_feel_worthless_the_way_you_are_now?.y",
    "Do_you_feel_full_of_energy?.y",
    "Do_you_feel_that_your_situation_is_hopeless?.y",
    "Do_you_think_that_most_people_are_better_off_than_you_are?.y",
    "TimePoint",
    "I_feel_fatigued",
    "I_feel_weak_all_over",
    "I_feel_listless_('washed_out')",
    "I_feel_tired",
    "I_have_trouble_starting_things_because_I_am_tired",
    "I_have_trouble_finishing_things_because_I_am_tired",
    "I_have_energy",
    "I_am_able_to_do_my_usual_activities",
    "I_need_to_sleep_during_the_day",
    "I_am_too_tired_to_eat",
    "I_need_help_doing_my_usual_activities",
    "I_am_frustrated_by_being_too_tired_to_do_the_things_I_want_to_do",
    "I_have_to_limit_my_social_activity_because_I_am_tired",
    "FACIT_Fatigue_Scale_Total_(prorated,_if_answers_missing)_",
    "Are_you_basically_satisfied_with_your_life?",
    "Have_you_dropped_many_of_your_activities_and_interests?",
    "Do_you_feel_that_your_life_is_empty?",
    "Do_you_often_get_bored?",
    "Are_you_in_good_spirits_most_of_the_time?",
    "Are_you_afraid_that_something_bad_is_going_to_happen_to_you?",
    "Do_you_feel_happy_most_of_the_time?",
    "Do_you_often_feel_helpless?",
    "Do_you_prefer_to_stay_at_home,_rather_than_going_out_and_doing_things?",
    "Do_you_feel_that_you_have_more_problems_with_memory_than_most?",
    "Do_you_think_it_is_wonderful_to_be_alive_now?",
    "Do_you_feel_worthless_the_way_you_are_now?",
    "Do_you_feel_full_of_energy?",
    "Do_you_feel_that_your_situation_is_hopeless?",
    "Do_you_think_that_most_people_are_better_off_than_you_are?",
    "Is_ECG_available? 🔒",
    "Are_labs_available? 🔒",
    "LangFact_V3",
    "WMF_V3",
    "ProcSpeed_V3",
    "MemFact_V3",
    "Visuospatial_V3",
    "GlobalTest_V3",
    "GlobalDomain_V3",
    "Impaired_at_V3",
    "LangFact_V4",
    "WMF_V4",
    "ProcSpeed_V4",
    "MemFact_V4",
    "Visuospatial_V4",
    "GlobalTest_V4",
    "GlobalDomain_V4",
    "Impaired_at_V4",
    "LangFact_V5",
    "WMF_V5",
    "ProcSpeed_V5",
    "MemFact_V5",
    "Visuospatial_V5",
    "GlobalTest_V5",
    "GlobalDomain_V5",
    "Impaired_at_V5",
    "Normed_MoCA_V3",
    "Normed_MoCA_V4",
    "Normed_MoCA_V2",
    "stroke_time_of_day 🔒",
]


def main():
    config = ModelConfig(
        csv_path="C:\\Users\\rufus\\OneDrive - The University of Manchester\\PDRA\\Sequencing\\stoke_imapact_data\\Manchester_WithMeans_250612.csv",
        save_dir="C:\\Users\\rufus\\OneDrive - The University of Manchester\\PDRA\\Sequencing\\stoke_imapact_data\\",
        index_col="Study_ID",
        target_feature_y="Normed_MoCA_V5",
        columns_to_drop=col_to_remove,
    )

    pipeline = ModelPipeline(config)
    pipeline.run()


if __name__ == "__main__":
    main()
